### ISSUE TITLE
Setup Basic Project Structure

### ISSUE THREAD

**Issue by rimidalvk** [rimidalvk/SMM_Stats_to_GS_parser#1]
Description: Set up the basic project file structure as described in the project documentation. Each of the files should contain the following pseudocode (append and modify as you think appropriate. Add info about libraries and solutions):

main.py:

python
Copy code
# Import necessary modules
# Define main function
    # Fetch configuration from Google Sheets
    # Log the start of a new cycle
    # Fetch posts and comments links from Google Sheets
    # Filter links based on configuration
    # For each link, call appropriate scraper
    # Store scraped data back into Google Sheets
    # Plan the next cycle
    # Log the end of the current cycle
# Call main function
scrapers/linkedin_scraper.py:

python
Copy code
# Define function to scrape LinkedIn
    # Simulate human-like behavior
    # Scrape data
    # Return scraped data
scrapers/reddit_scraper.py:

python
Copy code
# Define function to scrape Reddit
    # Simulate human-like behavior
    # Scrape data
    # Return scraped data
scrapers/medium_scraper.py:

python
Copy code
# Define function to scrape Medium
    # Simulate human-like behavior
    # Scrape data
    # Return scraped data
integrations/google_sheets.py:

python
Copy code
# Define functions to interact with Google Sheets
    # Function to fetch data
    # Function to store data
utils/config.py:

python
Copy code
# Define function to fetch configuration from Google Sheets
utils/logger.py:

python
Copy code
# Define functions to log different types of data
    # Function to log start of a cycle
    # Function to log end of a cycle
    # Function to log errors
Once the basic project structure is set up with this pseudocode, developers can then proceed to fill out the actual code under each function, following the guidance provided by the pseudocode. This ensures all developers are following the same plan and helps to keep the project organized and understandable for all team members.

**Comment by Mobiss11** [comment]
Залил базовую структуру

**Comment by rimidalvk** [comment]
@Mazon7 можете пожалуйста посмотреть эту задачу, оценить что там залил Игорь, либо смержить в мэйн, либо добавить. В описании задачи уже есть псевдокод - его можно перенести в файлы. Спасибо!
